version: '2'
services:
  lint:
    image: buildkite/plugin-linter:latest
    command: ['--id', 'juandiegopalomino/junit-annotate-local']
    volumes:
      - ".:/plugin"
  plugin:
    image: buildkite/plugin-tester:latest@sha256:476a1024936901889147f53d2a3d8e71e99d76404972d583825514f5608083dc
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:3.1-alpine@sha256:c5acbb8bcc57cc3cb8da7f28077ec23c9c05217f26bd4e156d7b87df6dcf0c00
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"