name: Junit Annotate Local
description: Annotates your build using JUnit XML reports from local files
author: https://github.com/rippling
requirements:
  - docker
configuration:
  properties:
    directory:
      type: string
    always-annotate:
      type: boolean
    context:
      type: string
    failure-format:
      type: string
      enum:
        - classname
        - file
    fail-build-on-error:
      type: boolean
    job-uuid-file-pattern:
      type: string
    report-slowest:
      type: integer
    append:
      type: boolean
    verbose:
      type: boolean
  required:
    - directory
  additionalProperties: false
